"""Site content for Accurate Weighing Systems.

Everything the pages show lives here: company details, categories, industries,
services and the product catalogue (taken from the IndiaMart listing).
Edit this file and run `python3 build.py` to regenerate every page.
"""

IMG = "https://5.imimg.com/data5/"

COMPANY = {
    "name": "Accurate Weighing Systems",
    "short": "Accurate",
    "tagline": "Weighing scales, balances & systems — sales, service and integration since 2011",
    "owner": "Satnam Singh Pannu",
    "founded": 2011,
    "city": "Ludhiana, Punjab",
    # TODO: replace with the full shop address before launch
    "address": "Ludhiana, Punjab, India",
    # IndiaMart shows a routed number; replace with the direct mobile / WhatsApp number
    "phone": "+91 80482 61489",
    "phone_raw": "918048261489",
    "whatsapp": "918048261489",
    # TODO: replace with the real business email
    "email": "info@accu1india.com",
    "gst": "03DHOPS2543Q1ZN",
    "iec": "DHOPS2543Q",
    "udyam": "UDYAM-PB-12-****732",
    "legal": "Proprietorship",
    "payment": "Cash, Credit Card, Cheque, DD, Online",
    "shipping": "By Road",
    "hours": "Mon – Sat, 10:00 AM – 7:00 PM",
    "indiamart": "https://www.indiamart.com/accurateweighingsystems/",
    "map_query": "Ludhiana, Punjab",
}

BRANDS = [
    {"name": "Essae", "desc": "India's leading maker of electronic scales, balances and printing scales. Our largest range — retail, industrial, precision and systems."},
    {"name": "CAS", "desc": "Korean weighing brand known for price-computing, label-printing and platform scales used by retail chains."},
    {"name": "DIGI", "desc": "Japanese label-printing and retail weighing systems for supermarkets, meat, bakery and packaged-food counters."},
    {"name": "Tula / Swift", "desc": "Value-for-money bench, platform, check-weighing and crane scales for workshops and factories. Authorised distributor of Tula Digital (I) Pvt. Ltd."},
]

# slug, name, short description, icon
CATEGORIES = [
    ("retail-scales", "Retail & Counter Scales", "Table-top, price-computing and counter scales for kirana, sweet shops and supermarkets.", "store"),
    ("printing-scales", "Printing & Label Scales", "Receipt, barcode-label and data printers that bill straight off the scale.", "printer"),
    ("platform-scales", "Platform & Bench Scales", "Mild-steel and SS304 platforms from 30 kg to 500 kg for godowns and factories.", "platform"),
    ("industrial-scales", "Industrial & Counting Scales", "Counting, check-weighing and flame-proof scales for production lines.", "factory"),
    ("crane-scales", "Crane & Hanging Scales", "Wireless crane scales up to 20 ton for steel yards, foundries and loading bays.", "crane"),
    ("precision-balances", "Precision & Lab Balances", "Milligram-accurate balances with wind shields for labs, pharma and QC.", "flask"),
    ("jewellery-scales", "Jewellery & Gold Scales", "10 mg gold scales and precision balances for jewellers and bullion traders.", "gem"),
    ("weighing-systems", "Weighing Systems & Indicators", "Tank weighers, indicators and ERP-ready weighing systems built to site.", "cpu"),
]

# Ranges on the IndiaMart profile with no listed models yet: shown as enquiry cards
ON_REQUEST = [
    ("Electronic Weighbridges", "Pit and pit-less weighbridges with software and printer.", "truck"),
    ("Moisture Analyzers", "Halogen moisture analysers for grain, pharma and food.", "droplet"),
    ("POS Systems & Components", "Touch POS terminals, cash drawers and receipt printers.", "monitor"),
    ("Marble Inlay Table-Top Scales", "Premium marble-top counter scales for sweet and dry-fruit shops.", "store"),
]

INDUSTRIES = [
    ("retail", "Retail & Kirana", "Fast, legal-for-trade counter and price-computing scales that customers can read from both sides.", "store", ["retail-scales", "printing-scales"]),
    ("jewellery", "Jewellery & Bullion", "10 mg gold scales and carat balances with stable readings, even under shop lighting and AC draughts.", "gem", ["jewellery-scales", "precision-balances"]),
    ("pharma", "Pharma & Laboratories", "Precision balances, flame-proof scales and calibration records for QC and GMP audits.", "flask", ["precision-balances", "industrial-scales"]),
    ("chemical", "Chemical & Paints", "Flame-proof and SS scales for hazardous, corrosive and wash-down areas.", "beaker", ["industrial-scales", "platform-scales"]),
    ("food", "Food Processing & Sweets", "IP68 waterproof SS304 scales and label printers for hygienic, wash-down areas.", "wheat", ["platform-scales", "printing-scales"]),
    ("textile", "Textile & Hosiery", "Yarn and fabric-roll platform scales, GSM balances and counting scales for Ludhiana's mills.", "shirt", ["platform-scales", "precision-balances"]),
    ("engineering", "Engineering & Auto Parts", "Counting scales for fasteners and components, crane scales for heavy parts.", "cog", ["industrial-scales", "crane-scales"]),
    ("logistics", "Logistics & Warehousing", "Platform scales, crane scales and weighbridges for dispatch and inward checks.", "truck", ["platform-scales", "crane-scales"]),
]

SERVICES = [
    ("Installation & Demo", "Delivery, levelling, set-up and a hands-on demo for your staff at your site.", "wrench"),
    ("Calibration & Stamping", "Calibration with certified test weights and support with Legal Metrology verification and re-stamping.", "badge"),
    ("Repair & AMC", "Quick repair for all major brands, genuine spares and annual maintenance contracts for multi-scale sites.", "shield"),
    ("ERP / SAP / Busy Integration", "Special indicators and software that push weights straight into SAP, Tally/Busy or your own ERP — no manual entry.", "cpu"),
]

WHY_US = [
    ("Multi-brand choice", "Essae, CAS, DIGI and Tula under one roof — we suggest the right scale, not just the one we stock."),
    ("15 years in Ludhiana", "Serving shops, labs and factories across Punjab since 2011."),
    ("Service after sale", "Our own engineers for installation, calibration, repair and AMC."),
    ("Fair, transparent pricing", "Competitive prices, GST invoices and all payment modes accepted."),
    ("Integration expertise", "Weighing that talks to SAP, ERP and Busy — a rare skill among dealers."),
    ("Licensed dealer", "Government licensed to deal in weighing instruments, small to large."),
]


def p(slug, name, brand, cat, price, img, specs, desc, industries, badge=None, unit="Piece"):
    return dict(slug=slug, name=name, brand=brand, cat=cat, price=price, unit=unit,
                img=(IMG + img) if img else None, specs=specs, desc=desc,
                industries=industries, badge=badge)


PRODUCTS = [
    # ---------------- Retail & counter ----------------
    p("essae-ds-75-counter-scale", "Essae DS-75 Counter Weighing Scale", "Essae", "retail-scales", 10800, None,
      {"Capacity": "15 / 30 kg", "Accuracy": "2 / 5 g", "Display": "Green LED, front & back", "Application": "Sweet shops, grocery"},
      "A proven, simple and efficient counter scale that is easy to use and accurate — the everyday workhorse for sweet shops and grocery stores.",
      ["retail", "food"], "Trending"),
    p("essae-ds-515n", "Essae DS-515N Electronic Weighing Machine", "Essae", "retail-scales", 18290,
      "SELLER/Default/2022/9/SC/FK/HP/3338415/essae-electronic-weighing-machine-ds-515-125x125.jpeg",
      {"Capacity": "6 – 30 kg", "Body": "Stainless steel", "Display": "Green LED", "Power": "230 V AC, 50 Hz", "Battery": "6 V rechargeable, in-built charger"},
      "Stainless-steel retail scale with a microprocessor-based PCB, high accuracy, auto power-off and standby mode.",
      ["retail", "food"]),
    p("essae-dx-852-table-top", "Essae DX-852 Table Top Weight Machine", "Essae", "retail-scales", 18580,
      "SELLER/Default/2023/5/308666990/KN/ZB/EX/3338415/table-top-weight-machine-dx-852-125x125.png",
      {"Capacity": "3 kg", "Accuracy": "0.2 g", "Platform": "302 × 227 mm", "Display": "7-segment LED, front & back"},
      "Compact table-top scale for precise and dependable weighing at retail counters, labs and small workshops.",
      ["retail", "jewellery", "food"], "Trending"),
    p("essae-ds-852-0-5g", "Essae DS-852 Electronic Weighing Machine, 0.5 g", "Essae", "retail-scales", 18754,
      "SELLER/Default/2023/5/311934801/MK/IX/MQ/3338415/essaeds-852-electronic-weighing-machine-0-5g-125x125.jpg",
      {"Capacity": "15 kg", "Accuracy": "0.5 g", "Display": "Green VFD", "Features": "Battery backup, auto power-off"},
      "High-accuracy retail and packing scale with a bright VFD display and a strong, rugged platform.",
      ["retail", "food"]),
    p("pcs-price-computing-scale", "PCS Counting & Price Computing Scale", "Swift", "retail-scales", 11500,
      "SELLER/Default/2023/5/311935951/XR/AF/CF/3338415/pcs-counting-price-computing-scale-125x125.jpg",
      {"Capacity": "30 kg", "Accuracy": "2 g", "Display": "Green LED", "Power": "220 V"},
      "Price-computing and piece-counting in one machine — enter the rate and the scale shows the amount.",
      ["retail"]),
    p("retail-weighing-scale", "Retail Weighing Scale", "Swift", "retail-scales", 6750,
      "SELLER/Default/2023/5/305414593/DP/BO/WN/3338415/retail-weighing-scale-125x125.jpg",
      {"Type": "Counter scale", "Display": "LED", "Application": "Shops & stores"},
      "Budget-friendly counter scale for small shops, vegetable vendors and daily retail use.",
      ["retail"]),

    # ---------------- Printing ----------------
    p("essae-ds-252pr-receipt-printing", "Essae DS-252PR Receipt Printing Scale", "Essae", "printing-scales", 25600,
      "SELLER/Default/2021/7/JJ/EQ/QI/3338415/essae-ds-252pr-electronic-weighing-machine-125x125.jpg",
      {"Printer": "Built-in thermal receipt", "Accuracy": "2 / 5 g", "Capacity": "15.5 / 31 kg", "Application": "Retail billing"},
      "Weigh and print a receipt in one step — ideal for sweet shops, dry-fruit stores and meat counters.",
      ["retail", "food"], "Trending"),
    p("essae-si-810-printing-scale", "Essae SI-810 Digital Printing Scale", "Essae", "printing-scales", 46080,
      "OS/RP/TS/SELLER-3338415/printing-scale-125x125.png",
      {"Model": "SI-810", "Body": "Stainless steel", "Display": "Graphical dot-matrix LCD", "PLU memory": "5,000", "Clock": "Built-in RTC", "Power": "230 V AC, 50 Hz"},
      "Industrial printing scale with 5,000 PLU storage, calendar/clock and weight records for traceable dispatch.",
      ["food", "logistics", "engineering"], unit="PCS"),
    p("essae-dc-810-label-printing", "Essae DC-810 Label Printing Scale", "Essae", "printing-scales", 79540, None,
      {"Model": "DC-810", "Capacity": "50 kg", "Accuracy": "5 g", "Printer": "Integrated barcode label printer", "Connectivity": "Optional Wi-Fi / LAN for ERP"},
      "Counting, check-weighing and barcode labels in one scale, with optional Wi-Fi/LAN to send data to your ERP.",
      ["engineering", "logistics", "food"], "New"),
    p("tula-thermal-printer-scale", "Thermal Printer with Weighing Scale", "Tula", "printing-scales", 45550, None,
      {"Models": "TDP, TDJ", "Input": "Keyboard", "Database": "From SD card", "Features": "Supplier code, mfg. date on print"},
      "Weighing with thermal printing for inward/outward slips — pick items from an SD-card database and print dated slips.",
      ["logistics", "textile"], unit="Unit"),
    p("essae-dp-810-data-printer", "Essae DP-810 Data Printer", "Essae", "printing-scales", 55000,
      "SELLER/Default/2025/8/535332584/ZV/RO/HG/3338415/f37bd3d3-02e4-47c3-ab22-913e0fb1661e-125x125.jpg",
      {"Type": "Data printer", "Use with": "Essae scales and indicators"},
      "Add printed records to an existing Essae scale — weight slips for dispatch, QC and audit trails.",
      ["pharma", "logistics"]),

    # ---------------- Platform & bench ----------------
    p("essae-200kg-platform", "Essae 200 kg Single Load Cell Platform Scale", "Essae", "platform-scales", 21048,
      "SELLER/Default/2025/8/534037064/XC/IR/MQ/3338415/essae-200-kg-single-load-cell-platform-electronic-weighing-machine-125x125.jpg",
      {"Capacity": "200 kg", "Accuracy": "20 g", "Platform": "505 × 650 mm", "Platter / frame": "SS / mild steel", "Origin": "Made in India"},
      "Single-load-cell platform scale for godowns, dispatch and inward checks.",
      ["logistics", "textile", "engineering"], "New"),
    p("essae-ds-215hd", "Essae DS-215HD Heavy Duty Platform Scale", "Essae", "platform-scales", 22910,
      "SELLER/Default/2022/9/KT/TG/EN/3338415/ds-215-hd-heavy-duty-weighing-scale-500x500-125x125.jpg",
      {"Model": "DS-215HD", "Capacity": "75 / 150 kg", "Accuracy": "10 / 20 g", "Platform": "505 × 550 mm", "Display": "Green LED", "Calibration": "External"},
      "Heavy-duty platform with battery backup, auto power-off and standby mode — built for all-day industrial use.",
      ["engineering", "logistics", "textile"], "Trending"),
    p("ss-platform-weighing-scale", "SS Platform Weighing Scale 150 kg", "Swift", "platform-scales", 13500,
      "SELLER/Default/2023/5/305413698/SF/WQ/NL/3338415/ss-platform-weighing-scale-125x125.jpg",
      {"Capacity": "150 kg", "Platform": "505 × 550 mm", "Material": "Stainless steel", "Usage": "Industrial"},
      "Rust-free stainless steel platform for food, dairy and chemical areas.",
      ["food", "chemical"]),
    p("essae-ss304-weighing-scale", "Essae SS304 Weighing Scale 30 kg", "Essae", "platform-scales", 36500, None,
      {"Capacity": "30 kg", "Platform": "400 × 400 mm", "Material": "Fully SS304", "Usage": "Food & chemical industry"},
      "Fully SS304 construction for hygienic and corrosive environments.",
      ["food", "chemical", "pharma"]),
    p("essae-dx-450ep-waterproof", "Essae DX-450EP Waterproof Weighing Scale", "Essae", "platform-scales", 35550,
      "SELLER/Default/2026/7/630332854/ZN/VU/NQ/3338415/essae-waterproof-weighing-scale-dx-450ep-125x125.jpg",
      {"Capacity": "30 kg", "Accuracy": "2 g", "Protection": "IP68 waterproof", "Housing": "Food-grade SS304", "Display": "Both sides"},
      "IP68-certified waterproof table-top scale for wet and harsh use — fish, meat, dairy and wash-down areas.",
      ["food", "chemical"], "New"),
    p("swift-bench-scale", "Swift Bench Scale", "Swift", "platform-scales", 9950,
      "SELLER/Default/2023/5/311936105/MX/ME/EF/3338415/swift-bench-scale-125x125.jpg",
      {"Accuracy": "10 g", "Display": "Green LED", "Features": "Auto calibration, auto zero, overload protection, multiple units"},
      "Heavy-duty, high-precision load cell in a fast, accurate and reliable bench scale.",
      ["engineering", "logistics"]),
    p("swift-platform-scale", "Swift Chequered Platform Scale", "Swift", "platform-scales", 11550, None,
      {"Accuracy": "10 g", "Platform": "Heavy steel chequered plate", "Features": "Large display, counting", "Use": "Office, business, industrial"},
      "Rugged construction with a heavy chequered steel plate and counting capability.",
      ["logistics", "engineering"]),
    p("tdp-150k-platform-scale", "TDP-150K Platform Scale", "Swift", "platform-scales", 10750,
      "SELLER/Default/2023/5/311936892/KJ/RJ/HV/3338415/tdp-150k-platform-scale-125x125.jpg",
      {"Capacity": "150 kg", "Material": "Stainless steel", "Origin": "Made in India"},
      "Value platform scale for industrial and warehouse weighing.",
      ["logistics", "textile"]),

    # ---------------- Industrial & counting ----------------
    p("essae-dc-85-counting-scale", "Essae DC-85 Counting Scale", "Essae", "industrial-scales", 23120,
      "SELLER/Default/2023/5/311934887/KP/BE/RE/3338415/counting-scale-dc-85-125x125.jpg",
      {"Capacity": "30 kg", "Accuracy": "2 g", "Display": "Bright green VFD", "Usage": "Industrial"},
      "High-accuracy yet simple counting scale — count screws, fasteners and components by weight.",
      ["engineering", "textile"], "Trending"),
    p("essae-dc-85n-851n", "Essae DC-85N / DC-851N Counting Scale", "Essae", "industrial-scales", 27360, None,
      {"Models": "DC-85N / DC-851N", "Body": "ABS plastic", "Application": "Piece counting"},
      "Updated counting scale with separate weight, unit-weight and count displays.",
      ["engineering"]),
    p("essae-dc-85-0-05g", "Essae DC-85 Electronic Weighing Machine", "Essae", "industrial-scales", 18700,
      "SELLER/Default/2023/5/311935444/AK/DV/AN/3338415/essae-0-05-g-electronic-weighing-machine-dc-85-125x125.jpg",
      {"Capacity": "30 kg", "Display": "Vacuum fluorescent", "Features": "Auto power-off, standby"},
      "Industrial weighing machine with a microprocessor-based PCB and bright VFD display.",
      ["engineering"]),
    p("essae-ds-852-industrial", "Essae DS-852 Industrial Weighing Machine", "Essae", "industrial-scales", 14500,
      "SELLER/Default/2023/5/311936618/OH/YL/FM/3338415/essae-ds-852-0-05-g-electronic-weighing-machine-125x125.jpg",
      {"Capacity": "15 kg", "Accuracy": "0.5 g", "Display": "Green VFD", "Features": "Battery backup, auto power-off"},
      "Strong, rugged platform with high accuracy for packing and QC tables.",
      ["engineering", "food"]),
    p("tdj-30k-check-weighing", "TDJ-30K Check Weighing Scale", "Swift", "industrial-scales", 11500, None,
      {"Model": "TDJ", "Capacity": "1 – 30 kg", "Calibration": "External"},
      "Set upper and lower limits and check packs for over/under weight on the line.",
      ["food", "engineering"]),
    p("check-weighing-hooter-lamp", "Check Weighing Scale with Hooter Lamp", "Swift", "industrial-scales", 11590, None,
      {"Alarm": "Hooter + lamp, 1 m audible range", "Mounting": "Horizontal / vertical", "Voltage": "220 V", "Features": "Auto calibration, auto zero, overload protection"},
      "Audible and visual alarm for out-of-tolerance weights on busy packing lines.",
      ["food", "engineering"], unit="PCS"),
    p("swift-flame-proof-scale", "Flame-Proof Weighing Scale", "Swift", "industrial-scales", 26600, None,
      {"Enclosure": "Flame-proof SS box", "Capacity": "Above 100 kg", "Display": "LED", "Ideal for": "Pharma & chemical"},
      "Flame-proof electronic scale with SS load-cell signal box for hazardous areas.",
      ["pharma", "chemical"]),

    # ---------------- Crane ----------------
    p("essae-crane-scale", "Essae Crane Scale", "Essae", "crane-scales", 349180,
      "SELLER/Default/2023/5/304837697/ND/PO/NX/3338415/essae-crane-scale-electronic-weighing-machine-125x125.jpg",
      {"Type": "Electronic crane scale", "Application": "Steel, foundry, logistics"},
      "Heavy-capacity crane scale for weighing loads while lifting — saves a separate weighing step.",
      ["engineering", "logistics"]),
    p("tula-crane-scale-caston-ii", "Tula Caston-II Crane Scale", "Tula", "crane-scales", 38700, None,
      {"Model": "Caston-II", "Capacity": "5 / 10 / 15 / 20 ton", "Display": "30 mm red LED", "Features": "Battery backup"},
      "Economical industrial crane scale with a large red display readable from the floor.",
      ["engineering", "logistics"]),

    # ---------------- Precision & lab ----------------
    p("essae-aj-1200e", "Essae AJ-1200E Precision Balance", "Essae", "precision-balances", 49938,
      "SELLER/Default/2023/5/305412411/IR/YA/PY/3338415/essae-electronic-weighing-machine-aj-1200e-125x125.jpg",
      {"Capacity": "1,200 g", "Display": "Digital", "Series": "AJ (tuning-fork sensor)"},
      "Tuning-fork precision balance with fast, stable readings for labs and QC.",
      ["pharma", "textile", "jewellery"]),
    p("essae-aj-2200e", "Essae AJ-2200E Precision Balance", "Essae", "precision-balances", 50940, None,
      {"Capacity": "2,200 g", "Sensor": "Tuning-fork frequency sensing", "Application": "Industrial / lab"},
      "Tuning-fork sensing for long-term stability without frequent recalibration.",
      ["pharma", "chemical"]),
    p("essae-aj-3200e", "Essae AJ-3200E Precision Balance", "Essae", "precision-balances", 49245, None,
      {"Capacity": "3,200 g", "Calibration": "External", "Display height": "16.5 mm", "Power": "230 V AC, 50 Hz"},
      "Precision balance with a microprocessor-based PCB and high accuracy.",
      ["pharma", "textile"]),
    p("essae-aj-6200e", "Essae AJ-6200E Precision Balance", "Essae", "precision-balances", 77752, None,
      {"Capacity": "6,200 g", "Display height": "16.5 mm", "Application": "Industrial", "Power": "230 V AC, 50 Hz"},
      "Higher-capacity precision balance for formulation and batching.",
      ["pharma", "chemical"]),
    p("essae-aj-12000e", "Essae AJ-12000E Precision Balance", "Essae", "precision-balances", 44287,
      "SELLER/Default/2023/5/305411862/WG/IC/RE/3338415/essae-12000g-electronic-weighing-machine-aj-12000e-125x125.jpg",
      {"Capacity": "12,000 g", "Series": "AJ", "Application": "Industrial"},
      "12 kg precision balance for larger samples with lab-level accuracy.",
      ["pharma", "food"]),
    p("essae-shield-balance-320g", "Essae Shield Balance 320 g", "Essae", "precision-balances", 41200,
      "SELLER/Default/2023/5/305345216/YI/UQ/AP/3338415/essae-shield-electronic-weighing-machine-125x125.jpg",
      {"Capacity": "320 g", "Display": "LCD", "Features": "Draft shield, auto power-off"},
      "Draft-shield balance for fine weighing without air-current errors.",
      ["pharma", "jewellery"]),
    p("essae-wind-shield-420g", "Essae Wind Shield Balance 420 g", "Essae", "precision-balances", 41200,
      "SELLER/Default/2023/5/311936529/RN/OQ/OR/3338415/essae-wind-shield-electronic-weighing-machine-420-g-125x125.jpg",
      {"Capacity": "420 g", "Series": "AJ", "Display": "LCD", "Power": "230 V AC, 50 Hz"},
      "Wind-shield precision balance for labs and gem weighing.",
      ["pharma", "jewellery"]),
    p("essae-wind-shield-220g", "Essae Wind Shield Balance 220 g", "Essae", "precision-balances", 49000,
      "SELLER/Default/2023/5/311936638/GK/IW/XM/3338415/essae-wind-shield-electronic-weighing-machine-220-g-125x125.jpg",
      {"Capacity": "220 g", "Type": "Wind-shield balance"},
      "High-resolution analytical-style balance for small samples.",
      ["pharma"], unit="PCS"),
    p("digital-lab-weighing-scale", "Digital Lab Weighing Scale", "Essae", "precision-balances", 14860,
      "SELLER/Default/2021/6/ES/SJ/II/3338415/digital-lab-weighing-scale-125x125.jpeg",
      {"Type": "Laboratory balance", "Application": "Labs, schools, QC"},
      "Affordable lab balance for schools, colleges and routine QC.",
      ["pharma", "textile"]),

    # ---------------- Jewellery ----------------
    p("essae-ds-852g-gold-scale", "Essae DS-852G Digital Gold Scale", "Essae", "jewellery-scales", 18210,
      "SELLER/Default/2023/5/311934740/LD/FN/XZ/3338415/digital-gold-weighing-scales-125x125.jpg",
      {"Model": "DS-852G", "Accuracy": "10 mg", "Display": "Green VFD", "Power": "230 V AC, 50 Hz", "Battery": "6 V rechargeable"},
      "10 mg gold scale with battery backup and standby mode for jewellery counters.",
      ["jewellery"], "Trending"),
    p("essae-jx-jewellery-balance", "Essae JX Precision Balance for Jewellery", "Essae", "jewellery-scales", 20180,
      "SELLER/Default/2023/5/308667917/QO/KD/OU/3338415/precision-balance-for-jewelry-jx-125x125.png",
      {"Series": "JX", "Application": "Gold, silver, gems"},
      "Precision jewellery balance with carat and gram modes.",
      ["jewellery"]),

    # ---------------- Systems ----------------
    p("essae-tank-weigher", "Essae Tank Weigher", "Essae", "weighing-systems", 106220,
      "SELLER/Default/2023/5/311934844/SF/WD/LT/3338415/essae-tank-weigher-125x125.png",
      {"Type": "Load-cell tank / silo weighing", "Output": "Indicator, optional PLC / ERP"},
      "Turn any tank, hopper or silo into a scale — for batching, stock control and dosing.",
      ["chemical", "food", "pharma"]),
    p("essae-di-60-indicator", "Essae DI-60 Weighing Indicator", "Essae", "weighing-systems", None,
      "SELLER/Default/2025/8/535322509/PO/ZB/GA/3338415/1fa5da71-f708-45ab-bea0-696544258b09-125x125.jpg",
      {"Type": "Weighing indicator", "Use": "Platforms, tanks, custom systems"},
      "Indicator for building custom platforms and systems; pairs with printers and PCs.",
      ["engineering", "logistics"]),
]

FAQS = {
    "_default": [
        ("Is this scale legal for trade?", "Yes. We supply Legal Metrology-approved models for trade use and help with verification and stamping."),
        ("Do you provide installation and training?", "Yes — delivery, installation and a short demo are included for Ludhiana; for other cities we arrange it on request."),
        ("What warranty do I get?", "Manufacturer's warranty applies (typically 1 year). We handle warranty service locally so you don't need to ship the scale."),
        ("Is the price final?", "Prices shown are indicative and exclude GST and delivery. Send an enquiry for the latest price and offers."),
    ],
    "weighing-systems": [
        ("Can the weight go directly into our ERP?", "Yes. We supply indicators and software that send weights to SAP, Busy, Tally or custom ERP over RS-232, USB or LAN."),
        ("Do you design systems to our site?", "Yes — we survey the site, suggest load cells and indicators, and install and calibrate on location."),
    ],
    "precision-balances": [
        ("How often should a precision balance be calibrated?", "For labs, we recommend an internal check daily and a certified calibration at least once a year. We provide both."),
    ],
}
